
package co.igb.apiSoul.client.wsClientesBodegas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsClientesBodegasSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsClientesBodegasSoap {


    /**
     * 
     * @param pOrdenSalida
     * @param pCodigoSalida
     * @param pNroPedido
     * @param pContrasena
     * @param pSede
     * @param pObservaciones
     * @param pPrioridad
     * @param pFechaEstimadaDespacho
     * @param pFechaOrden
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.RespOrdenSalida
     */
    @WebMethod(operationName = "OrdenSalida", action = "http://tempuri.org/OrdenSalida")
    @WebResult(name = "OrdenSalidaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OrdenSalida", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.OrdenSalida")
    @ResponseWrapper(localName = "OrdenSalidaResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.OrdenSalidaResponse")
    public RespOrdenSalida ordenSalida(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pContrasena", targetNamespace = "http://tempuri.org/")
        String pContrasena,
        @WebParam(name = "pSede", targetNamespace = "http://tempuri.org/")
        String pSede,
        @WebParam(name = "pPrioridad", targetNamespace = "http://tempuri.org/")
        String pPrioridad,
        @WebParam(name = "pFechaOrden", targetNamespace = "http://tempuri.org/")
        String pFechaOrden,
        @WebParam(name = "pFechaEstimadaDespacho", targetNamespace = "http://tempuri.org/")
        String pFechaEstimadaDespacho,
        @WebParam(name = "pObservaciones", targetNamespace = "http://tempuri.org/")
        String pObservaciones,
        @WebParam(name = "pNroPedido", targetNamespace = "http://tempuri.org/")
        String pNroPedido,
        @WebParam(name = "pCodigoSalida", targetNamespace = "http://tempuri.org/")
        String pCodigoSalida,
        @WebParam(name = "pOrdenSalida", targetNamespace = "http://tempuri.org/")
        ArrayOfClsBEOrdenSalidaWS pOrdenSalida);

    /**
     * 
     * @param pContrasena
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.RespConsultaInventario
     */
    @WebMethod(operationName = "ConsultaInventario", action = "http://tempuri.org/ConsultaInventario")
    @WebResult(name = "ConsultaInventarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaInventario", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultaInventario")
    @ResponseWrapper(localName = "ConsultaInventarioResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultaInventarioResponse")
    public RespConsultaInventario consultaInventario(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pContrasena", targetNamespace = "http://tempuri.org/")
        String pContrasena);

    /**
     * 
     * @param pNroOrdenCompra
     * @param pContrasena
     * @param pDocumentoTransporte
     * @param pUsuario
     * @param pCargueInventario
     * @return
     *     returns co.igb.apiSoul.client.RespCargueInventario
     */
    @WebMethod(operationName = "CargueInventario", action = "http://tempuri.org/CargueInventario")
    @WebResult(name = "CargueInventarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargueInventario", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.CargueInventario")
    @ResponseWrapper(localName = "CargueInventarioResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.CargueInventarioResponse")
    public RespCargueInventario cargueInventario(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pContrasena", targetNamespace = "http://tempuri.org/")
        String pContrasena,
        @WebParam(name = "pDocumentoTransporte", targetNamespace = "http://tempuri.org/")
        String pDocumentoTransporte,
        @WebParam(name = "pNroOrdenCompra", targetNamespace = "http://tempuri.org/")
        String pNroOrdenCompra,
        @WebParam(name = "pCargueInventario", targetNamespace = "http://tempuri.org/")
        ArrayOfClsBECargueInventarioWS pCargueInventario);

    /**
     * 
     * @param pContrasena
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.RespConsultaInventarioBodega
     */
    @WebMethod(operationName = "ConsultaInventarioBodega", action = "http://tempuri.org/ConsultaInventarioBodega")
    @WebResult(name = "ConsultaInventarioBodegaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaInventarioBodega", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultaInventarioBodega")
    @ResponseWrapper(localName = "ConsultaInventarioBodegaResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultaInventarioBodegaResponse")
    public RespConsultaInventarioBodega consultaInventarioBodega(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pContrasena", targetNamespace = "http://tempuri.org/")
        String pContrasena);

    /**
     * 
     * @param pContrasena
     * @param pDocTransporte
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.RespConsultaConteo
     */
    @WebMethod(operationName = "ConsultaConteosxDocTransporte", action = "http://tempuri.org/ConsultaConteosxDocTransporte")
    @WebResult(name = "ConsultaConteosxDocTransporteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaConteosxDocTransporte", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultaConteosxDocTransporte")
    @ResponseWrapper(localName = "ConsultaConteosxDocTransporteResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultaConteosxDocTransporteResponse")
    public RespConsultaConteo consultaConteosxDocTransporte(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pContrasena", targetNamespace = "http://tempuri.org/")
        String pContrasena,
        @WebParam(name = "pDocTransporte", targetNamespace = "http://tempuri.org/")
        String pDocTransporte);

    /**
     * 
     * @param pTipoConteo
     * @param pContrasena
     * @param pNroFactura
     * @param pUsuario
     * @return
     *     returns co.igb.apiSoul.client.RespReporteConteo
     */
    @WebMethod(operationName = "ReporteConteo", action = "http://tempuri.org/ReporteConteo")
    @WebResult(name = "ReporteConteoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReporteConteo", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ReporteConteo")
    @ResponseWrapper(localName = "ReporteConteoResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ReporteConteoResponse")
    public RespReporteConteo reporteConteo(
        @WebParam(name = "pUsuario", targetNamespace = "http://tempuri.org/")
        String pUsuario,
        @WebParam(name = "pContrasena", targetNamespace = "http://tempuri.org/")
        String pContrasena,
        @WebParam(name = "pNroFactura", targetNamespace = "http://tempuri.org/")
        String pNroFactura,
        @WebParam(name = "pTipoConteo", targetNamespace = "http://tempuri.org/")
        int pTipoConteo);

    /**
     * 
     * @param usuario
     * @param consecutivoSalida
     * @param contrasena
     * @return
     *     returns co.igb.apiSoul.client.RespConsultarEstadoPaquete
     */
    @WebMethod(operationName = "ConsultarEstadoPaquete", action = "http://tempuri.org/ConsultarEstadoPaquete")
    @WebResult(name = "ConsultarEstadoPaqueteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarEstadoPaquete", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultarEstadoPaquete")
    @ResponseWrapper(localName = "ConsultarEstadoPaqueteResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultarEstadoPaqueteResponse")
    public RespConsultarEstadoPaquete consultarEstadoPaquete(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "ConsecutivoSalida", targetNamespace = "http://tempuri.org/")
        String consecutivoSalida);

    /**
     * 
     * @param usuario
     * @param contrasena
     * @param consecutivoCaja
     * @return
     *     returns co.igb.apiSoul.client.RespConsultarEstadoPaquete
     */
    @WebMethod(operationName = "ConsultarEstadoPaquetexCaja", action = "http://tempuri.org/ConsultarEstadoPaquetexCaja")
    @WebResult(name = "ConsultarEstadoPaquetexCajaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarEstadoPaquetexCaja", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultarEstadoPaquetexCaja")
    @ResponseWrapper(localName = "ConsultarEstadoPaquetexCajaResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultarEstadoPaquetexCajaResponse")
    public RespConsultarEstadoPaquete consultarEstadoPaquetexCaja(
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "ConsecutivoCaja", targetNamespace = "http://tempuri.org/")
        String consecutivoCaja);

    /**
     * 
     * @param tramitada
     * @param usuario
     * @param ordenCompra
     * @param numeroBp
     * @param detalleOrden
     * @param fechaOrdenHasta
     * @param consecutivoSalida
     * @param contrasena
     * @param fechaOrdenDesde
     * @return
     *     returns co.igb.apiSoul.client.RespSalidasEverfit
     */
    @WebMethod(operationName = "ConsultarOrdenesSalidaEverfit", action = "http://tempuri.org/ConsultarOrdenesSalidaEverfit")
    @WebResult(name = "ConsultarOrdenesSalidaEverfitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarOrdenesSalidaEverfit", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultarOrdenesSalidaEverfit")
    @ResponseWrapper(localName = "ConsultarOrdenesSalidaEverfitResponse", targetNamespace = "http://tempuri.org/", className = "co.igb.apiSoul.client.ConsultarOrdenesSalidaEverfitResponse")
    public RespSalidasEverfit consultarOrdenesSalidaEverfit(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "contrasena", targetNamespace = "http://tempuri.org/")
        String contrasena,
        @WebParam(name = "fechaOrdenDesde", targetNamespace = "http://tempuri.org/")
        String fechaOrdenDesde,
        @WebParam(name = "fechaOrdenHasta", targetNamespace = "http://tempuri.org/")
        String fechaOrdenHasta,
        @WebParam(name = "numeroBp", targetNamespace = "http://tempuri.org/")
        String numeroBp,
        @WebParam(name = "consecutivoSalida", targetNamespace = "http://tempuri.org/")
        String consecutivoSalida,
        @WebParam(name = "ordenCompra", targetNamespace = "http://tempuri.org/")
        String ordenCompra,
        @WebParam(name = "detalleOrden", targetNamespace = "http://tempuri.org/")
        String detalleOrden,
        @WebParam(name = "tramitada", targetNamespace = "http://tempuri.org/")
        boolean tramitada);

}
