
package co.igb.apiSoul.client.wsClientesBodegas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsClientesBodegas", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://soul.magnum.com.co/Mercurio/ServiciosWeb/Clientes/wsClientesBodegas.asmx?wsdl")
public class WsClientesBodegas
    extends Service
{

    private final static URL WSCLIENTESBODEGAS_WSDL_LOCATION;
    private final static WebServiceException WSCLIENTESBODEGAS_EXCEPTION;
    private final static QName WSCLIENTESBODEGAS_QNAME = new QName("http://tempuri.org/", "wsClientesBodegas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://soul.magnum.com.co/Mercurio/ServiciosWeb/Clientes/wsClientesBodegas.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCLIENTESBODEGAS_WSDL_LOCATION = url;
        WSCLIENTESBODEGAS_EXCEPTION = e;
    }

    public WsClientesBodegas() {
        super(__getWsdlLocation(), WSCLIENTESBODEGAS_QNAME);
    }

    public WsClientesBodegas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WsClientesBodegasSoap
     */
    @WebEndpoint(name = "wsClientesBodegasSoap")
    public WsClientesBodegasSoap getWsClientesBodegasSoap() {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasSoap"), WsClientesBodegasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsClientesBodegasSoap
     */
    @WebEndpoint(name = "wsClientesBodegasSoap")
    public WsClientesBodegasSoap getWsClientesBodegasSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasSoap"), WsClientesBodegasSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WsClientesBodegasSoap
     */
    @WebEndpoint(name = "wsClientesBodegasSoap12")
    public WsClientesBodegasSoap getWsClientesBodegasSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasSoap12"), WsClientesBodegasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsClientesBodegasSoap
     */
    @WebEndpoint(name = "wsClientesBodegasSoap12")
    public WsClientesBodegasSoap getWsClientesBodegasSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasSoap12"), WsClientesBodegasSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WsClientesBodegasHttpGet
     */
    @WebEndpoint(name = "wsClientesBodegasHttpGet")
    public WsClientesBodegasHttpGet getWsClientesBodegasHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasHttpGet"), WsClientesBodegasHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsClientesBodegasHttpGet
     */
    @WebEndpoint(name = "wsClientesBodegasHttpGet")
    public WsClientesBodegasHttpGet getWsClientesBodegasHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasHttpGet"), WsClientesBodegasHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns WsClientesBodegasHttpPost
     */
    @WebEndpoint(name = "wsClientesBodegasHttpPost")
    public WsClientesBodegasHttpPost getWsClientesBodegasHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasHttpPost"), WsClientesBodegasHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsClientesBodegasHttpPost
     */
    @WebEndpoint(name = "wsClientesBodegasHttpPost")
    public WsClientesBodegasHttpPost getWsClientesBodegasHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsClientesBodegasHttpPost"), WsClientesBodegasHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCLIENTESBODEGAS_EXCEPTION!= null) {
            throw WSCLIENTESBODEGAS_EXCEPTION;
        }
        return WSCLIENTESBODEGAS_WSDL_LOCATION;
    }

}
