
package co.igb.b1ws.client.deliverynote;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeliveryNotesService", targetNamespace = "DeliveryNotesService", wsdlLocation = "http://192.168.10.102/B1WS/WebReferences/DeliveryNotesService.wsdl")
public class DeliveryNotesService
    extends Service
{

    private final static URL DELIVERYNOTESSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYNOTESSERVICE_EXCEPTION;
    private final static QName DELIVERYNOTESSERVICE_QNAME = new QName("DeliveryNotesService", "DeliveryNotesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.102/B1WS/WebReferences/DeliveryNotesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYNOTESSERVICE_WSDL_LOCATION = url;
        DELIVERYNOTESSERVICE_EXCEPTION = e;
    }

    public DeliveryNotesService() {
        super(__getWsdlLocation(), DELIVERYNOTESSERVICE_QNAME);
    }

    public DeliveryNotesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYNOTESSERVICE_QNAME, features);
    }

    public DeliveryNotesService(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYNOTESSERVICE_QNAME);
    }

    public DeliveryNotesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYNOTESSERVICE_QNAME, features);
    }

    public DeliveryNotesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryNotesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "DeliveryNotesServiceSoap")
    public DeliveryNotesServiceSoap getDeliveryNotesServiceSoap() {
        return super.getPort(new QName("DeliveryNotesService", "DeliveryNotesServiceSoap"), DeliveryNotesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "DeliveryNotesServiceSoap")
    public DeliveryNotesServiceSoap getDeliveryNotesServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("DeliveryNotesService", "DeliveryNotesServiceSoap"), DeliveryNotesServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "DeliveryNotesServiceSoap12")
    public DeliveryNotesServiceSoap getDeliveryNotesServiceSoap12() {
        return super.getPort(new QName("DeliveryNotesService", "DeliveryNotesServiceSoap12"), DeliveryNotesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "DeliveryNotesServiceSoap12")
    public DeliveryNotesServiceSoap getDeliveryNotesServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("DeliveryNotesService", "DeliveryNotesServiceSoap12"), DeliveryNotesServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYNOTESSERVICE_EXCEPTION!= null) {
            throw DELIVERYNOTESSERVICE_EXCEPTION;
        }
        return DELIVERYNOTESSERVICE_WSDL_LOCATION;
    }

}
