
package co.igb.b1ws.client.purchasedeliverynote;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseDeliveryNotesService", targetNamespace = "PurchaseDeliveryNotesService", wsdlLocation = "http://192.168.10.102/B1WS/WebReferences/PurchaseDeliveryNotesService.wsdl")
public class PurchaseDeliveryNotesService
    extends Service
{

    private final static URL PURCHASEDELIVERYNOTESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PURCHASEDELIVERYNOTESSERVICE_EXCEPTION;
    private final static QName PURCHASEDELIVERYNOTESSERVICE_QNAME = new QName("PurchaseDeliveryNotesService", "PurchaseDeliveryNotesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.102/B1WS/WebReferences/PurchaseDeliveryNotesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEDELIVERYNOTESSERVICE_WSDL_LOCATION = url;
        PURCHASEDELIVERYNOTESSERVICE_EXCEPTION = e;
    }

    public PurchaseDeliveryNotesService() {
        super(__getWsdlLocation(), PURCHASEDELIVERYNOTESSERVICE_QNAME);
    }

    public PurchaseDeliveryNotesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEDELIVERYNOTESSERVICE_QNAME, features);
    }

    public PurchaseDeliveryNotesService(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEDELIVERYNOTESSERVICE_QNAME);
    }

    public PurchaseDeliveryNotesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEDELIVERYNOTESSERVICE_QNAME, features);
    }

    public PurchaseDeliveryNotesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseDeliveryNotesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseDeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "PurchaseDeliveryNotesServiceSoap")
    public PurchaseDeliveryNotesServiceSoap getPurchaseDeliveryNotesServiceSoap() {
        return super.getPort(new QName("PurchaseDeliveryNotesService", "PurchaseDeliveryNotesServiceSoap"), PurchaseDeliveryNotesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseDeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "PurchaseDeliveryNotesServiceSoap")
    public PurchaseDeliveryNotesServiceSoap getPurchaseDeliveryNotesServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("PurchaseDeliveryNotesService", "PurchaseDeliveryNotesServiceSoap"), PurchaseDeliveryNotesServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseDeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "PurchaseDeliveryNotesServiceSoap12")
    public PurchaseDeliveryNotesServiceSoap getPurchaseDeliveryNotesServiceSoap12() {
        return super.getPort(new QName("PurchaseDeliveryNotesService", "PurchaseDeliveryNotesServiceSoap12"), PurchaseDeliveryNotesServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseDeliveryNotesServiceSoap
     */
    @WebEndpoint(name = "PurchaseDeliveryNotesServiceSoap12")
    public PurchaseDeliveryNotesServiceSoap getPurchaseDeliveryNotesServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("PurchaseDeliveryNotesService", "PurchaseDeliveryNotesServiceSoap12"), PurchaseDeliveryNotesServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEDELIVERYNOTESSERVICE_EXCEPTION!= null) {
            throw PURCHASEDELIVERYNOTESSERVICE_EXCEPTION;
        }
        return PURCHASEDELIVERYNOTESSERVICE_WSDL_LOCATION;
    }

}
