
package co.igb.b1ws.client.purchaseorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseOrdersService", targetNamespace = "PurchaseOrdersService", wsdlLocation = "http://192.168.10.102/B1WS/WebReferences/PurchaseOrdersService.wsdl")
public class PurchaseOrdersService
    extends Service
{

    private final static URL PURCHASEORDERSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PURCHASEORDERSSERVICE_EXCEPTION;
    private final static QName PURCHASEORDERSSERVICE_QNAME = new QName("PurchaseOrdersService", "PurchaseOrdersService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.102/B1WS/WebReferences/PurchaseOrdersService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEORDERSSERVICE_WSDL_LOCATION = url;
        PURCHASEORDERSSERVICE_EXCEPTION = e;
    }

    public PurchaseOrdersService() {
        super(__getWsdlLocation(), PURCHASEORDERSSERVICE_QNAME);
    }

    public PurchaseOrdersService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEORDERSSERVICE_QNAME, features);
    }

    public PurchaseOrdersService(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEORDERSSERVICE_QNAME);
    }

    public PurchaseOrdersService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEORDERSSERVICE_QNAME, features);
    }

    public PurchaseOrdersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseOrdersService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrdersServiceSoap
     */
    @WebEndpoint(name = "PurchaseOrdersServiceSoap")
    public PurchaseOrdersServiceSoap getPurchaseOrdersServiceSoap() {
        return super.getPort(new QName("PurchaseOrdersService", "PurchaseOrdersServiceSoap"), PurchaseOrdersServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrdersServiceSoap
     */
    @WebEndpoint(name = "PurchaseOrdersServiceSoap")
    public PurchaseOrdersServiceSoap getPurchaseOrdersServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("PurchaseOrdersService", "PurchaseOrdersServiceSoap"), PurchaseOrdersServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrdersServiceSoap
     */
    @WebEndpoint(name = "PurchaseOrdersServiceSoap12")
    public PurchaseOrdersServiceSoap getPurchaseOrdersServiceSoap12() {
        return super.getPort(new QName("PurchaseOrdersService", "PurchaseOrdersServiceSoap12"), PurchaseOrdersServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrdersServiceSoap
     */
    @WebEndpoint(name = "PurchaseOrdersServiceSoap12")
    public PurchaseOrdersServiceSoap getPurchaseOrdersServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("PurchaseOrdersService", "PurchaseOrdersServiceSoap12"), PurchaseOrdersServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEORDERSSERVICE_EXCEPTION!= null) {
            throw PURCHASEORDERSSERVICE_EXCEPTION;
        }
        return PURCHASEORDERSSERVICE_WSDL_LOCATION;
    }

}
